{% set name = "wasmtime" %}
{% set version = "41.0.0" %}

package:
  name: {{ name }}-py
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fc2aaacf3ba794eac8baeb739939b2f7903e12d6b78edddc0b7f3ac3a9af6dfc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - python                                     # [build_platform != target_platform]
    - cross-python_{{ target_platform }}         # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - wasmtime
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bytecodealliance/wasmtime-py
  summary: A WebAssembly runtime powered by Wasmtime
  description: |
    Python embedding of Wasmtime, a fast and secure runtime for WebAssembly.
    Wasmtime is a standalone runtime for WebAssembly, using Cranelift as its
    code generator. It runs WebAssembly code outside of the web browser and
    can be used both as a command-line utility or as an embedded runtime.
  license: Apache-2.0 WITH LLVM-exception
  license_file: LICENSE
  doc_url: https://docs.wasmtime.dev/lang-python.html
  dev_url: https://github.com/bytecodealliance/wasmtime-py

extra:
  recipe-maintainers:
    - rxm7706
